customhost = "employee.cowailclo8mg.us-east-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "addemployeestr"
customregion = "us-east-2"
